import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the build and gitignored, so CI never sees it and a local count that
    // included it disagreed with CI by 87.
    "public/sw.js",
  ]),
  {
    // The lint-to-zero campaign (soma#958, 2026-09-13) is finished: every rule that had a
    // backlog is an error again and CI runs with `--max-warnings 0`. There is no warning tier
    // left to hide in, so a new finding fails the build rather than raising a cap.
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": [
        "error", // the underscore prefix marks an intentionally unused binding
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
    },
  },
]);

export default eslintConfig;
